[buildPlans.RyanTerm]
family           = "Ryan Term"
spacing          = "term"
serifs           = "sans"
noCvSs           = false
exportGlyphNames = true

[buildPlans.RyanTerm.variants]
inherits = "ss05"

[buildPlans.RyanTerm.widths.Normal]
shape = 600
menu  = 5
css   = "normal"

[buildPlans.RyanTerm.namingOverride]
version      = "%%version%%"
copyright    = "Copyright 2015-{{currentYear}}, Renzhi Li (aka. Belleve Invis, belleve@typeof.net). Copyright 2024-{{currentYear}}, Ryan Cao (hello@ryanccn.dev)."
manufacturer = "Ryan Cao"
designer     = "Belleve Invis"
description  = "Ryan's homemade Iosevka build."
urlVendor    = "https://github.com/ryanccn/ryan-mono"
urlDesigner  = "https://typeof.net/Iosevka/"
licence      = "This font software is licenced under the SIL Open Font Licence, Version 1.1. This licence is available with a FAQ at: http://scripts.sil.org/OFL. This font software is distributed on an 'AS IS' basis, without warranties or conditions of any kind, either express or implied. See the SIL Open Font licence for the specific language, permissions and limitations governing your use of this font software."
licenceURL   = "https://openfontlicense.org/"
